/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface Cart {
  id?: number;
  products?: Array<Product>;
  userId?: number;
}
