/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addCart } from '../fn/carts/add-cart';
import { AddCart$Params } from '../fn/carts/add-cart';
import { Cart } from '../models/cart';
import { deleteCart } from '../fn/carts/delete-cart';
import { DeleteCart$Params } from '../fn/carts/delete-cart';
import { getAllCarts } from '../fn/carts/get-all-carts';
import { GetAllCarts$Params } from '../fn/carts/get-all-carts';
import { getCartById } from '../fn/carts/get-cart-by-id';
import { GetCartById$Params } from '../fn/carts/get-cart-by-id';
import { updateCart } from '../fn/carts/update-cart';
import { UpdateCart$Params } from '../fn/carts/update-cart';

@Injectable({ providedIn: 'root' })
export class CartsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllCarts()` */
  static readonly GetAllCartsPath = '/carts';

  /**
   * Get all carts.
   *
   * Retrieve a list of all available carts.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCarts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCarts$Response(params?: GetAllCarts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Cart>>> {
    return getAllCarts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all carts.
   *
   * Retrieve a list of all available carts.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCarts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCarts(params?: GetAllCarts$Params, context?: HttpContext): Observable<Array<Cart>> {
    return this.getAllCarts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Cart>>): Array<Cart> => r.body)
    );
  }

  /** Path part for operation `addCart()` */
  static readonly AddCartPath = '/carts';

  /**
   * Add a new cart.
   *
   * Create a new cart.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addCart()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCart$Response(params: AddCart$Params, context?: HttpContext): Observable<StrictHttpResponse<Cart>> {
    return addCart(this.http, this.rootUrl, params, context);
  }

  /**
   * Add a new cart.
   *
   * Create a new cart.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addCart$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCart(params: AddCart$Params, context?: HttpContext): Observable<Cart> {
    return this.addCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<Cart>): Cart => r.body)
    );
  }

  /** Path part for operation `getCartById()` */
  static readonly GetCartByIdPath = '/carts/{id}';

  /**
   * Get a single cart.
   *
   * Retrieve details of a specific cart by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCartById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCartById$Response(params: GetCartById$Params, context?: HttpContext): Observable<StrictHttpResponse<Cart>> {
    return getCartById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a single cart.
   *
   * Retrieve details of a specific cart by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCartById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCartById(params: GetCartById$Params, context?: HttpContext): Observable<Cart> {
    return this.getCartById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Cart>): Cart => r.body)
    );
  }

  /** Path part for operation `updateCart()` */
  static readonly UpdateCartPath = '/carts/{id}';

  /**
   * Update a cart.
   *
   * Update an existing cart by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCart()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCart$Response(params: UpdateCart$Params, context?: HttpContext): Observable<StrictHttpResponse<Cart>> {
    return updateCart(this.http, this.rootUrl, params, context);
  }

  /**
   * Update a cart.
   *
   * Update an existing cart by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCart$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCart(params: UpdateCart$Params, context?: HttpContext): Observable<Cart> {
    return this.updateCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<Cart>): Cart => r.body)
    );
  }

  /** Path part for operation `deleteCart()` */
  static readonly DeleteCartPath = '/carts/{id}';

  /**
   * Delete a cart.
   *
   * Delete a specific cart by ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCart$Response(params: DeleteCart$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCart(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a cart.
   *
   * Delete a specific cart by ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCart(params: DeleteCart$Params, context?: HttpContext): Observable<void> {
    return this.deleteCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
